# Generated by Django 5.1.4 on 2025-01-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('prio', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('assignedTo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('await_feedback', 'Await Feedback'), ('done', 'Done')], default='todo', max_length=20)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
