# Generated by Django 5.1.4 on 2025-01-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_subtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=5)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=15)),
                ('info', models.CharField(max_length=20)),
            ],
        ),
    ]
