# Generated by Django 5.1.4 on 2025-02-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0002_alter_task_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
