# Generated by Django 5.1.4 on 2025-01-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0005_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('await_feedback', 'Await Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(default=list),
        ),
    ]
