# Generated by Django 5.1.4 on 2025-01-14 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0008_subtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
    ]
