# Generated by Django 5.1.4 on 2025-01-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0010_alter_subtask_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
